services:
    mssql:
        build: ./mssql
        environment:
            SA_PASSWORD: "P@ssword123!"
            ACCEPT_EULA: "Y"
            MSSQL_AGENT_ENABLED: "true"
        ports:
            - "5443:1433"
        container_name: InterviewChallengeSql
        hostname: mssql
