// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using InterviewChallenge.Data.Models.Db.dboSchema;


namespace InterviewChallenge.Data.Models.Db.dboSchema;

public partial class SyndicationFeed
{
    public long Id { get; set; }

    public int SyndicationSourceId { get; set; }

    public bool? IsActive { get; set; }

    public string Sha512 { get; set; }

    public string SourceId { get; set; }

    public string ChannelId { get; set; }

    public string VideoId { get; set; }

    public string Title { get; set; }

    public string Summary { get; set; }

    public string Description { get; set; }

    public string Author { get; set; }

    public string Link { get; set; }

    public string Enclosure { get; set; }

    public string ContentEncoded { get; set; }

    public string Thumbnail { get; set; }

    public DateTime? PublishedDate { get; set; }

    public DateTime? PublishedDateUpdated { get; set; }

    public DateTime LastUpdated { get; set; }

    public DateTime DateCreated { get; set; }

    public virtual ICollection<SyndicationFeedToCategory> SyndicationFeedToCategories { get; set; } = new List<SyndicationFeedToCategory>();

    public virtual SyndicationSource SyndicationSource { get; set; }
}