// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using InterviewChallenge.Data.Models.Db.dboSchema;


namespace InterviewChallenge.Data.Models.Db.dboSchema;

public partial class SyndicationSource
{
    public int Id { get; set; }

    public bool? IsActive { get; set; }

    public int IntervalSeconds { get; set; }

    public string Title { get; set; }

    public string BaseUri { get; set; }

    public string Copyright { get; set; }

    public string Description { get; set; }

    public DateTime? LastRunDate { get; set; }

    public DateTime DateCreated { get; set; }

    public DateTime LastUpdated { get; set; }

    public virtual ICollection<FeedRunLog> FeedRunLogs { get; set; } = new List<FeedRunLog>();

    public virtual ICollection<SyndicationFeed> SyndicationFeeds { get; set; } = new List<SyndicationFeed>();

    public virtual ICollection<SyndicationToCategory> SyndicationToCategories { get; set; } = new List<SyndicationToCategory>();
}