// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using InterviewChallenge.Data.Models.Db.dboSchema;


namespace InterviewChallenge.Data.Models.Db.dboSchema;

public partial class SyndicationFeedToCategory
{
    public Guid Id { get; set; }

    public long SyndicationFeedId { get; set; }

    public int CategoryId { get; set; }

    public virtual Category Category { get; set; }

    public virtual SyndicationFeed SyndicationFeed { get; set; }
}